# Generated by Django 5.1.4 on 2026-04-28 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=520, unique=True)),
                ("excerpt", models.TextField(max_length=1000)),
                ("body", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("published", "Publicado")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categorias",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
    ]
