# Generated by Django 5.1.4 on 2026-05-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_seed_pop_culture_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_caption',
            field=models.CharField(blank=True, default='', help_text='Legenda da imagem de capa (autor da foto, contexto).', max_length=300),
        ),
    ]
