# Generated by Django 5.1.4 on 2026-04-28 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(help_text="Motivo formal do banimento.")),
                (
                    "trigger_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem/conteúdo específico que originou o banimento (exibido em destaque).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = permanente.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("unbanned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "bans",
                "ordering": ["-created_at"],
            },
        ),
    ]
