# Generated by Django 5.1.4 on 2026-05-04 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('unsubscribe_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='newsletter__email_9b0a94_idx')],
            },
        ),
    ]
